# Generated by Django 6.0.7 on 2026-07-26 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
