# Generated by Django 6.0.7 on 2026-10-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('Java', 'Java'), ('PHP', 'PHP'), ('Python', 'Python'), ('ADBMS', 'ADBMS'), ('Spring', 'Spring'), ('C', 'C'), ('C++', 'C++'), ('ML', 'ML'), ('Docker', 'Docker'), ('Other', 'Other')], default='Java', max_length=50),
        ),
    ]
